development:
  adapter: postgresql
  encoding: unicode

  database: <Heroku Postgres database>
  pool: 5
  username: <Heroku Postgres username>
  password: <Heroku Postgres password>

  host: localhost
  port: 5432

test:
  adapter: postgresql
  encoding: unicode
  database: <Heroku Postgres database>
  pool: 5
  username: <Heroku Postgres username>
  password: <Heroku Postgres password>

  host: localhost
  port: 5432
